/* Generated By:JavaCC: Do not edit this line. Parser.java */
package parser;
import ast.*; import ast.operations.references.ASTId;import ast.operations.references.ASTLet;import ast.operations.references.ASTNew;import ast.operations.references.ASTRef;import ast.value.*; import ast.operations.arithmetic.*; import ast.operations.relational.*;

public class Parser implements ParserConstants {

  final public ASTNode Start() throws ParseException {
  ASTNode e;
    e = logicOps();
    jj_consume_token(EL);
                          {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode logicOps() throws ParseException {
 ASTNode e1, e2;
    e1 = BoolOps();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
    case OR:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        jj_consume_token(AND);
        e2 = logicOps();
                              e1 = new ASTAnd(e1,e2);
        break;
      case OR:
        jj_consume_token(OR);
        e2 = logicOps();
                             e1 = new ASTOr(e1,e2);
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
      {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode BoolOps() throws ParseException {
 ASTNode e1, e2;
    e1 = Expr();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQREL:
    case GT:
    case GEQT:
    case LT:
    case LEQT:
    case DIFF:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQREL:
        jj_consume_token(EQREL);
        e2 = BoolOps();
                               e1 = new ASTEq(e1,e2);
        break;
      case GT:
        jj_consume_token(GT);
        e2 = BoolOps();
                            e1 = new ASTGt(e1,e2);
        break;
      case GEQT:
        jj_consume_token(GEQT);
        e2 = BoolOps();
                              e1 = new ASTGeq(e1,e2);
        break;
      case LT:
        jj_consume_token(LT);
        e2 = BoolOps();
                            e1 = new ASTLt(e1,e2);
        break;
      case LEQT:
        jj_consume_token(LEQT);
        e2 = BoolOps();
                              e1 = new ASTLeq(e1,e2);
        break;
      case DIFF:
        jj_consume_token(DIFF);
        e2 = BoolOps();
                              e1 = new ASTDiff(e1,e2);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
      {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Expr() throws ParseException {
  ASTNode e1, e2;
    e1 = Term();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
    case MINUS:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        e2 = Expr();
                            e1 = new ASTAdd(e1,e2);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        e2 = Expr();
                             e1 = new ASTSub(e1,e2);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
       {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Term() throws ParseException {
  ASTNode e1, e2;
    e1 = Fact();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIMES:
    case DIV:
    case EQUALS:
    case ATRIB:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
        jj_consume_token(TIMES);
        e2 = Term();
                             e1 = new ASTMult(e1,e2);
        break;
      case DIV:
        jj_consume_token(DIV);
        e2 = Term();
                           e1 = new ASTDiv(e1,e2);
        break;
      case ATRIB:
        jj_consume_token(ATRIB);
        e2 = Expr();
                             e1 = new ASTRef(e2);
        break;
      case EQUALS:
        jj_consume_token(EQUALS);
        e2 = Expr();
                              e1 = new ASTInt(Integer.parseInt(e2.toString()));
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
       {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Let() throws ParseException {
  ASTNode e1, e2;
    jj_consume_token(LPAR);
    e1 = Term();
    jj_consume_token(RPAR);
    jj_consume_token(IN);
    e2 = Expr();
                                                 {if (true) return new ASTLet(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Fact() throws ParseException {
  Token x; ASTNode e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Num:
      x = jj_consume_token(Num);
              {if (true) return new ASTInt(Integer.parseInt(x.image));}
      break;
    case BOOL:
      x = jj_consume_token(BOOL);
                {if (true) return new ASTBool(Boolean.parseBoolean(x.image));}
      break;
    case NOT:
      jj_consume_token(NOT);
      e = Fact();
                      {if (true) return new ASTNot(e);}
      break;
    case MINUS:
      jj_consume_token(MINUS);
      e = Fact();
                     {if (true) return new ASTNeg(e);}
      break;
    case LPAR:
      jj_consume_token(LPAR);
      e = Expr();
      jj_consume_token(RPAR);
                              {if (true) return e;}
      break;
    case LET:
      jj_consume_token(LET);
      e = Let();
                     {if (true) return e;}
      break;
    case DEREF:
      jj_consume_token(DEREF);
      e = Expr();
                        {if (true) return new ASTRef(e);}
      break;
    case NEW:
      jj_consume_token(NEW);
      e = Term();
                      {if (true) return new ASTNew(e);}
      break;
    case Id:
      x = jj_consume_token(Id);
              {if (true) return new ASTId(new ASTString(x.image));}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x600000,0x600000,0xfc000,0xfc000,0x60,0x60,0x8002180,0x8002180,0x16901250,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[29];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 29; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
