/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int LPAR = 10;
  /** RegularExpression Id. */
  int RPAR = 11;
  /** RegularExpression Id. */
  int EF = 12;
  /** RegularExpression Id. */
  int SEMCOL = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int EXIT = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int EQREL = 17;
  /** RegularExpression Id. */
  int GT = 18;
  /** RegularExpression Id. */
  int GEQT = 19;
  /** RegularExpression Id. */
  int LT = 20;
  /** RegularExpression Id. */
  int LEQT = 21;
  /** RegularExpression Id. */
  int DIFF = 22;
  /** RegularExpression Id. */
  int DEREF = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int LET = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int THEN = 28;
  /** RegularExpression Id. */
  int ELSE = 29;
  /** RegularExpression Id. */
  int END = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int IN = 33;
  /** RegularExpression Id. */
  int NEW = 34;
  /** RegularExpression Id. */
  int FUN = 35;
  /** RegularExpression Id. */
  int FUNTYPE = 36;
  /** RegularExpression Id. */
  int TYPE = 37;
  /** RegularExpression Id. */
  int ARROWRIGHT = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int PRINT = 40;
  /** RegularExpression Id. */
  int PRINTLN = 41;
  /** RegularExpression Id. */
  int ATRIB = 42;
  /** RegularExpression Id. */
  int Id = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\";;\"",
    "\";\"",
    "<BOOL>",
    "\"exit\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"let\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"end\"",
    "\"while\"",
    "\"do\"",
    "\"in\"",
    "\"new\"",
    "\"fun\"",
    "\":\"",
    "<TYPE>",
    "\"->\"",
    "\"~\"",
    "\"print\"",
    "\"println\"",
    "\":=\"",
    "<Id>",
    "\",\"",
  };

}
